package koya.backend;

import koya.backend.KoyaAssets;
import koya.backend.songs.Song;
#if INCLUDE_GIT
import koya.backend.macros.Git;
#end
import koya.frontend.ui.ArrowUI;
import koya.frontend.scenes.freeplay.*;
import flixel.util.FlxColor;
import lime.app.Application;

class Constants
{
	/**
		Mod Version
	**/
	public static var VERSION(get, never):String;

	static function get_VERSION():String
	{
		return Application.current.meta.get('version') + VERSION_SUFFIX;
	}

	/**
		Suffix for `VERSION`
	**/
	public static var VERSION_SUFFIX(get, never):String;

	static function get_VERSION_SUFFIX():String
	{
		#if EMPTY_VERSION_SUFFIX
		return '';
		#end

		var suffix:String = '';

		#if INCLUDE_GIT
		suffix += ' (${Git.gimmeSuffix()})';
		#end

		#if playtesting
		suffix += ' [PLAYTEST]';
		#end

		return suffix;
	}

	/**
		Desired window title
	**/
	public static var WINDOW_TITLE(get, never):String;

	static function get_WINDOW_TITLE():String
	{
		return 'Funkin\' Koya' + #if (DEBUG_ASTERISK) '*' #else '' #end;
	}

	/**
		Song "Generated by" Field Prefix
	**/
	public static var SONG_GENERATED_BY_PREFIX(get, never):String;

	static function get_SONG_GENERATED_BY_PREFIX():String
	{
		return '${Constants.WINDOW_TITLE} ${Constants.VERSION} | ';
	}

	/**
		Song Chart Format
	**/
	public static var SONG_FORMAT(get, never):String;

	static function get_SONG_FORMAT():String
		return getSongFormatFromVersion(Song.SWAGVERSION);

	/**
		Receive the song format for version: `version`

		@param version the target version
	**/
	public static function getSongFormatFromVersion(version:Int)
	{
		// koya chart format
		// koyachartformat
		// koyta

		return 'koyta_$version';
	}
}
