name: Build CI

on:
  workflow_dispatch:
  push:
    paths:
      - "**.hx"

jobs:
  buildWindows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: krdlab/setup-haxe@v2.0.2
        with:
          haxe-version: 4.3.7
      - name: compile Windows
        run: |
          haxelib --global install hmm
          haxelib --global run hmm setup
          haxelib run hmm install
          haxelib list
          haxelib run lime build windows

      - uses: actions/upload-artifact@v6.0.0
        with:
          name: Windows Build
          path: export/release/windows/bin

  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: krdlab/setup-haxe@v2.0.2
        with:
          haxe-version: 4.3.7
      - name: compile Linux
        run: |
          sudo add-apt-repository ppa:haxe/releases -y
          sudo apt-get update
          sudo apt-get install gcc-multilib g++-multilib haxe -y
          haxelib --global install hmm
          haxelib --global run hmm setup
          haxelib run hmm install
          haxelib list
          haxelib run lime build linux

      - uses: actions/upload-artifact@v6.0.0
        with:
          name: Linux Build
          path: export/release/linux/bin

  buildMac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: krdlab/setup-haxe@v2.0.2
        with:
          haxe-version: 4.3.7
      - name: compile Mac
        run: |
          haxelib --global install hmm
          haxelib --global run hmm setup
          haxelib run hmm install
          haxelib list
          haxelib run lime build mac

      - uses: actions/upload-artifact@v6.0.0
        with:
          name: MacOS Build
          path: export/release/macos/bin
